# Generated by Django 4.2.4 on 2023-09-04 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 11, 13, 34, 55, 884294, tzinfo=datetime.timezone.utc)),
        ),
    ]
